import { Request, Response } from "express";
import { mentorAgentService } from "./mentor-agent.service";
import { sendSuccess, sendError } from "../../utils/apiResponse";
import { logger } from "../../utils/logger";


export const mentorController = {
  /**
   * Handle chat interactions with the AI Mentor
   */
  chat: async (req: Request, res: Response) => {
    try {
      const userId = req.user?.userId;
      if (!userId) {
        return sendError(res, "Access token is required", 401);
      }
      const { interviewSessionId, questionId, message, currentCode } = req.body;

      if (!interviewSessionId || !questionId || !message) {
        return sendError(res, "Missing required fields: interviewSessionId, questionId, message", 400);
      }

      const result = await mentorAgentService.getMentorResponse(
        userId,
        interviewSessionId,
        questionId,
        message,
        currentCode || "",
        "general"
      );

      return sendSuccess(res, result, "Mentor response generated successfully", 200);
    } catch (error: any) {
      logger.error("Mentor Chat Error:", error);
      return sendError(res, error.message || "Failed to generate mentor response", 500);
    }
  },

  /**
   * Quick action: Request a hint
   */
  requestHint: async (req: Request, res: Response) => {
    try {
      const userId = req.user?.userId;
      if (!userId) {
        return sendError(res, "Access token is required", 401);
      }
      const { interviewSessionId, questionId, currentCode } = req.body;

      const message = "I'm stuck. Can you give me a small hint without revealing the entire solution?";

      const result = await mentorAgentService.getMentorResponse(
        userId,
        interviewSessionId,
        questionId,
        message,
        currentCode || "",
        "hint"
      );

      return sendSuccess(res, result, "Hint generated successfully", 200);
    } catch (error: any) {
      logger.error("Mentor Hint Error:", error);
      return sendError(res, error.message || "Failed to generate hint", 500);
    }
  },

  /**
   * Quick action: Debug code
   */
  debugCode: async (req: Request, res: Response) => {
    try {
      const userId = req.user?.userId;
      if (!userId) {
        return sendError(res, "Access token is required", 401);
      }
      const { interviewSessionId, questionId, currentCode, errorLogs } = req.body;

      const message = "My code isn't working as expected. Can you spot any logical flaws or syntax errors?";

      const result = await mentorAgentService.getMentorResponse(
        userId,
        interviewSessionId,
        questionId,
        message,
        currentCode || "",
        "debug",
        errorLogs
      );

      return sendSuccess(res, result, "Debug analysis generated successfully", 200);
    } catch (error: any) {
      logger.error("Mentor Debug Error:", error);
      return sendError(res, error.message || "Failed to debug code", 500);
    }
  },

  /**
   * Quick action: Complexity analysis
   */
  analyzeComplexity: async (req: Request, res: Response) => {
    try {
      const userId = req.user?.userId;
      if (!userId) {
        return sendError(res, "Access token is required", 401);
      }
      const { interviewSessionId, questionId, currentCode } = req.body;

      const message = "Can you analyze the time and space complexity of my current code?";

      const result = await mentorAgentService.getMentorResponse(
        userId,
        interviewSessionId,
        questionId,
        message,
        currentCode || "",
        "complexity"
      );

      return sendSuccess(res, result, "Complexity analysis generated successfully", 200);
    } catch (error: any) {
      logger.error("Mentor Complexity Error:", error);
      return sendError(res, error.message || "Failed to analyze complexity", 500);
    }
  },

  /**
   * SSE streaming endpoint — sends tokens as they're generated by Gemini.
   * Accepts same body as the other endpoints, plus an optional `mode` field.
   */
  stream: async (req: Request, res: Response) => {
    const userId = req.user?.userId;
    if (!userId) {
      res.status(401).json({ success: false, message: "Access token is required" });
      return;
    }

    const { interviewSessionId, questionId, currentCode, message, mode, errorLogs } = req.body;

    if (!interviewSessionId || !questionId) {
      res.status(400).json({ success: false, message: "Missing required fields: interviewSessionId, questionId" });
      return;
    }

    // Derive message and mode if not supplied (quick-action compatibility)
    const finalMessage = message || "I need help with this problem.";
    const finalMode: "hint" | "debug" | "test-case" | "complexity" | "general" =
      ["hint", "debug", "test-case", "complexity", "general"].includes(mode) ? mode : "general";

    // Set SSE headers
    res.setHeader("Content-Type", "text/event-stream");
    res.setHeader("Cache-Control", "no-cache");
    res.setHeader("Connection", "keep-alive");
    res.setHeader("X-Accel-Buffering", "no"); // Disable nginx buffering if used
    res.flushHeaders();

    try {
      for await (const token of mentorAgentService.getMentorResponseStream(
        userId,
        interviewSessionId,
        questionId,
        finalMessage,
        currentCode || "",
        finalMode,
        errorLogs
      )) {
        // Each SSE event carries a JSON-encoded token
        res.write(`data: ${JSON.stringify({ token })}\n\n`);
      }
      // Signal end of stream
      res.write(`data: ${JSON.stringify({ done: true })}\n\n`);
    } catch (err: any) {
      logger.error("Mentor Stream Error:", err);
      res.write(`data: ${JSON.stringify({ error: err.message || "Stream failed" })}\n\n`);
    } finally {
      res.end();
    }
  },
};
