import { InterviewSession, EvaluationReport } from "@prisma/client";
import { prisma } from "../../config/database";

type SessionWithReport = InterviewSession & { evaluation?: EvaluationReport | null };

export class InterviewsRepository {
  /**
   * Create a new interview session and an associated EvaluationReport if metrics are provided.
   */
  async createSession(
    userId: string,
    data: any,
    metrics?: any
  ): Promise<SessionWithReport> {
    const session = await prisma.interviewSession.create({
      data: {
        ...data,
        userId,
        evaluation: metrics
          ? {
              create: {
                correctness: metrics.correctness,
                speed: metrics.speed,
                architecture: metrics.architecture,
                communication: metrics.communication,
                feedback: "Generated by Practice Session",
                score: Math.round((metrics.correctness + metrics.speed + metrics.architecture + metrics.communication) / 4) || 0,
                strengths: [],
                weaknesses: [],
                recommendations: [],
              },
            }
          : undefined,
      },
      include: {
        evaluation: true,
      },
    });

    // Enforce max 7 sessions per user
    const allSessions = await prisma.interviewSession.findMany({
      where: { userId },
      orderBy: { createdAt: "desc" },
      select: { id: true },
    });

    if (allSessions.length > 7) {
      const idsToDelete = allSessions.slice(7).map((s) => s.id);
      await prisma.interviewSession.deleteMany({
        where: { id: { in: idsToDelete } },
      });
    }

    return session;
  }

  /**
   * Fetch all sessions for a user, paginated, newest first.
   */
  async getUserSessions(
    userId: string,
    page: number,
    limit: number
  ): Promise<{ sessions: SessionWithReport[]; total: number }> {
    const skip = (page - 1) * limit;

    const [sessions, total] = await Promise.all([
      prisma.interviewSession.findMany({
        where: { userId },
        skip,
        take: limit,
        orderBy: { createdAt: "desc" },
        include: { evaluation: true },
      }),
      prisma.interviewSession.count({ where: { userId } }),
    ]);

    return { sessions, total };
  }

  /**
   * Fetch a single session by ID
   */
  async getSessionById(id: string): Promise<SessionWithReport | null> {
    return prisma.interviewSession.findUnique({
      where: { id },
      include: { evaluation: true },
    });
  }

  /**
   * Delete a session by ID
   */
  async deleteSession(id: string): Promise<void> {
    await prisma.interviewSession.delete({
      where: { id },
    });
  }
}

export const interviewsRepository = new InterviewsRepository();
